name: e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  skeletonizer: ^1.4.3
  flutter_secure_storage: ^9.2.4
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
